version: '3'

services:

  barkom-database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=barkom_db
#      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3309:3306

  app:
    image: danylooliiarchyk/barkom:latest

    ports:
      - 8086:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://barkom-database:3306/barkom_db?autoReconnect=true&useSSL=false&characterEncoding=utf-8&characterSetResults=utf-8
    depends_on:
      - barkom-database