version: '3'

services:

  barkom-database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=barkom_db
#      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  app:
    image: barkom-app

    ports:
      - 8085:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://barkom-database:3306/barkom_db?autoReconnect=true&useSSL=false
    depends_on:
      - barkom-database